Algoritmo "Exercicio_Soma"
// Disciplina   : Lógica de Programação com JavaScript
// Professor   : Jailson
// Descrição   : Solicitar dois valores, somar e exibir o resultado
// Autor(a)    : Rafaela
// Data atual  : 29/08/2024
Var
   num1, num2: inteiro
   soma: inteiro

Inicio
   Escreva("Digite um número: ")
   Leia(num1)
   Escreva("Digite outro número: ")
   Leia(num2)
   soma <- num1 + num2
   Escreva("O resultado da sua soma é: ", soma)

Fimalgoritmo