Algoritmo "Exercicio6_E"
// Disciplina   : Logica de Programacao]
// Professor   : Jailson
// Descrição   : Solicitar um valor e exibir a area de um triangulo
// Autor(a)    : Rafaela Bernardes
// Data atual  : 03/09/2024
Var
   base, altura, area: real

Inicio
   Escreva("Digite o valor da base do triângulo: ")
   Leia(base)
   Escreva("Digite o valor da altura do triângulo: ")
   Leia(altura)

   area <- base * altura / 2

   Escreva("A area do triângulo é: ", area)
Fimalgoritmo