Algoritmo "Exercicio6_C"
// Disciplina   : [Lógica de Programação com JavaScript]
// Professor   : Jailson
// Descrição   : Ler as dimensões de um cículo, calcular e escrever a  área
// Autor(a)    : Rafaela
// Data atual  : 29/08/2024
Var
   valor, area: real

Inicio
   Escreva("Digite o valor em cm do círculo: ")
   Leia(valor)

   area <- (valor * valor) * pi

   Escreva("A área do círculo é: ", area)

Fimalgoritmo