Algoritmo "Exercicio5_A"
// Disciplina   : Lógica de Programação
// Professor   : Jailson
// Descrição   : Escreva um algoritmo para ler um valor (do teclado) e escrever (na tela) o seu antecessor.
// Autor(a)    : Rafaela Bernardes
// Data atual  : 29/08/2024
Var
   valor: inteiro
   
Inicio
   Escreva("Digite um número: ")
   Leia(valor)
   Escreva("O antecessor desse número é: ", valor - 1)

Fimalgoritmo