Algoritmo "Exercicio6_D"
// Disciplina   : Logica de Programacao com JavaScript
// Professor   : Jailson
// Descri??o   : Ler as dimensoes de um hexagono, calcular e escrever a sua area
// Autor(a)    : Rafaela
// Data atual  : 29/08/2024
Var
   lado, area: real

Inicio
   Escreva("Digite o valor do lado do hexagono: ")
   Leia(lado)

   area <-(3 * raizq(3) / 2) * lado^2

   Escreva("A área do hexagono é: ", area)

Fimalgoritmo