Algoritmo "Exercicio6_A"
// Disciplina   : [Lógica de Programação com JavaScript]
// Professor   : Jailson
// Descrição   : Ler as dimensões de um retângulo(base e altura), calcular e escrever a  área
// Autor(a)    : Rafaela
// Data atual  : 29/08/2024
Var
   base, altura, area: real

Inicio
   Escreva("Digite a base do retângulo: ")
   Leia(base)
   Escreva("Digite a altura do retângulo: ")
   Leia(altura)

   area <- base * altura

   Escreva("A área do retângulo é: ", area)

Fimalgoritmo