Algoritmo "Exercicio6_B"
// Disciplina   : [Lógica de Programação com JavaScript]
// Professor   : Jailson
// Descrição   : Ler as dimensões de um quadrado, calcular e escrever a  área do quadrado
// Autor(a)    : Rafaela
// Data atual  : 29/08/2024
Var
   lado, area: real

Inicio
   Escreva("Digite o lado do quadrado: ")
   Leia(lado)

   area <- lado * lado

   Escreva("A área do quadrado é: ", area)

Fimalgoritmo