Algoritmo "Exercicio15"
// Disciplina   : Lógica de Programação com JS
// Professor   : Jailson
// Descrição   : Ler um valor e escrever se é positivo ou negativo
// Autor(a)    : Rafaela
// Data atual  : 13/09/2024
Var
   numero: inteiro


Inicio
   Escreva("Digite um número Positivo OU Negativo: ")
   Leia(numero)

   se numero > 0 entao
      Escreva("Seu número é Positivo")
   senao
      Escreva("Seu número é Negativo")
   fimse


Fimalgoritmo