Algoritmo "ExercicioL05A - Pag66 "
// Disciplina   : Lógica de Programação com JS
// Professor   : Jailson
// Descrição   : Apresentar os quadrados dos números inteiros de 15 a 200.
// Autor(a)    : Rafaela Bernardes
// Data atual  : 16/09/2024
Var
   numero, quadrado: inteiro
Inicio
   Para numero de 15 ate 200 faca
      quadrado <- numero * numero
      EscrevaL("O quadrado de ", numero, " é: ", quadrado)
   Fimpara
Fimalgoritmo